feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  url:
    governamental: http://www.transparencia.gov.br/api-de-dados/orgaos-siafi